version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: vedanshu
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
